export const APP_MODE = {
  MAIN_MENU: 'MAIN_MENU',
  NEW_SESSION: 'NEW_SESSION',
  LOAD_SESSION: 'LOAD_SESSION',
  IMPORT_SESSION: 'IMPORT_SESSION',
  PLAYING: 'PLAYING',
};

const prefix = '@@APP_';

export const SET_VERTICAL_TIMELINE = `${prefix}SET_VERTICAL_TIMELINE`;

export const SET_MODE = `${prefix}SET_MODE`;
